### ISSUE TITLE
input-modifier does not install

### ISSUE THREAD

**Issue by TherinS** [tildearrow/input-modifier#1]
The download of input-modifier results in a .zip file instead of a tar.gz so that is an issue, but even worse is that the instructions say to run the installer from the top folder, but the folder name contains -master at the end, and also does not contain the "install" file.  I did copy and paste the files from the "/src/installer" folder to the top level and got the License to show up in the terminal, clicked  'q' to get the accept/decline of the License, and the install failed with the following:

" do you agree? (y/N) y
input-modifier is going to be installed. are you sure about this? (y/N) y
going ahead.
creating program directory...
extracting program...
tar: installdata.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now"

I am trying to get input-modifier to run because in the upgrade from Ubuntu 16.04 to 18.04 the Pystromo program I used for years for remapping the keys on my Nostromo n52 and Razer Tartarus ceased working.  I can actually tell the n52 DOES reprogram because it changes the LED lights but not the keys.

(not my project, just links to it)
https://github.com/TherinS/Pystromo

I hope you can help with input-modifier, but I really miss Pystromo, as it worked great for any USB input device the kernel recognized (mouse, gamepad, Belkin/Razer gamepads).

**Comment by tildearrow** [comment]
It seems you downloaded the source in ZIP format (as provided by the "Clone or download" button) Try downloading from [Releases](https://github.com/tildearrow/input-modifier/releases) instead.

(I will make it clear in the readme as well)

**Comment by TherinS** [comment]
Thanks for updating the instructions!  That helped alot; I was unaware of the 'Releases' section.

Continuing the installation and running issues I am seeing...

1) I did get it to run, but after adding the $USER to the 'input' group, I got permission denied  and a suggestion to add $USER to the 'input' group (pic 1).  After a reboot 'imodd' did start running with terminal output matching the instructions.  Would it be right to run 'sudo modprobe uinput' (or 'input') after adding $USER to the input group?

Installation and Startup README.md seems to be fine but..

2) The devices.md step says to run imod-cli under the /input-modifier/bin directory but the directory does not exist.  It DOES exist, however, inside the installdata.tar file in the input-modifier/bin directory (inside the tar file).  I am guessing that either the installer does not extract the installdata.tar file and put imod-cli where its supposed to go or there should be another step to installing input-modifer to make that happen manually.

I extracted the files and moved them up to the input-modifer directory but when I ran 'imod-cli' there from a terminal it returned "can't connect: connection refused"  (pic 2).  I verified it had execute permissions but that did not seem to make it run.

Pic_1
![input-modifier_pic1](https://user-images.githubusercontent.com/46469573/54873603-b30b7980-4daf-11e9-9e9a-6acab886b4c8.png)
 
Pic_2
![input-modifier_pic2](https://user-images.githubusercontent.com/46469573/54873605-b999f100-4daf-11e9-9780-e4ecfa858478.png)

I hope I am providing constructive feedback to help make input-modifier as approachable as possible from a new or inexperienced users' standpoint.

**Comment by tildearrow** [comment]
Thank you for your feedback, and pardon the late reply. ~~It seems that the uinput permissions issue still lingers...~~

~~While doing `sudo modprobe uinput` will most likely work around the issue, it isn't a real fix.~~

~~Can you please reboot and then run `ls -l /dev/uinput`? (before running imodd) I want to confirm whether this is the case.~~

Sorry again, I totally misinterpreted your message.
I will clarify that a re-login is needed before using the program in the next commit. Thanks for pointing out.

The reason why imod-cli won't work is because imodd has failed to start.

(by the way, I just fixed the documentation issue: b693718)

**Comment by tildearrow** [comment]
Clarifications added in [v1.3.2 release](https://github.com/tildearrow/input-modifier/releases/tag/v1.3.2).
