### ISSUE TITLE
listprofiles problem

### ISSUE THREAD

**Issue by tildearrow** [tildearrow/input-modifier#3]
From [this issue](https://github.com/tildearrow/input-modifier/issues/2#issuecomment-478294777):

> also,

> When I want to list the profiles available, the following is the returned results:

> listprofiles honey
> [info] client 6: listprofiles honey
> using device Honey Bee Nostromo SpeedPad2 .
> 
> teson
> Default
> Ready.
> I never made a 'teson' profile. I cannot "switchprofile" to teson, nor can I delete it as "delprofile" says it does not exist.

**Comment by TherinS** [comment]
Here is my config directory.  

[input-modifier-config-directory.tar.gz](https://github.com/tildearrow/input-modifier/files/3031950/input-modifier-config-directory.tar.gz)

**Comment by tildearrow** [comment]
I just found out the issue.
The listprofiles command uses directory listing functions to list all profiles, and then remove the ".json" extension, but for some reason the extension remover didn't work well with a profile named "test1".

Fixed in 4fb25decf427da3d873b9ab39d37fc88765dd471. v1.3.4 will be released soon with the fix.

**Comment by tildearrow** [comment]
v1.3.4 now released.
