### ISSUE TITLE
Clarify purpose / features

### ISSUE THREAD

**Issue by ngirard** [tildearrow/input-modifier#4]
Hi,

I just stumbled upon your project, which seems interesting, but after reading the README and browsing the docs I still doesn't have a clear picture of its purpose and most valuable features.

Would you mind expanding the README a bit, and perhaps explaining how it compares to Xdotool or Autokey ?

Thanks in advance !

**Comment by tildearrow** [comment]
Sure. Thank you for the suggestion!

The purpose of this project is to allow the user to assign actions to keys, which can come in handy if you want to do repetitive actions easily (e.g. tap a key repeatedly by simply holding it or launch a sequence of keys with a single keypress), launch applications using keys, disabling keys you don't want to be pressed by accident, mapping gaming keypads, etc.

The advantages of input-modifier over xdotool are:
- Interacts with the evdev input layer, which is lower-level than X.
- Works outside X, e.g. VT or Wayland.
The disadvantages are:
- You can't directly map a key to closing a window, or something that has to do with X (however, you can execute xdotool from input-modifier).

The advantages of input-modifier over AutoKey are: (although I've never used it)
- Is written in C++, which means less overhead than Python.
- Allows for doing things like remapping keys (besides executing applications and running macros) without resorting to complex hacks.
The disadvantages are:
- No GUI yet.
- Does not allow for DE-specific actions or X11-specific ones (but I am pretty sure it may be possible to use both programs in tandem).
