### ISSUE TITLE
invalid config file exception not handled which causes abort

### ISSUE THREAD

**Issue by LeoKira997** [tildearrow/input-modifier#8]
this is what happens when i try to run imodd

> [info] input-modifier v1.3.4
[info] scanning devices...
[info] starting device listener...
[info] initializing socket interface...
[info] removing remnants of dead daemon...
[info] initializing devices...
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)

**Comment by LeoKira997** [comment]
disregard, deleted config files and it worked fine, hate how i always figure things out after reporting/asking someone before they can respond...

**Comment by tildearrow** [comment]
~~Wait a moment. Please provide your configuration file as this is still a bug (unable to handle corrupted configuration).~~ Never mind. Bug fixed regardless by handling failure to parse config.
